language: java

env:
  - APIKEY_OSENV=00000000000000000000000000000042

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8

sudo: required

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue
